config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :events
  resources :users, only: %i[new create show]
  resource :session, only: %i[new create destroy]

  root 'events#index'

  get '/sign-in', to: 'sessions#new'
  get '/sign-up', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  # Associations
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :attendees, class_name: 'User'

  # scopes
  scope :upcoming_events, -> { where("date > ?", Time.now) }
  scope :previous_events, -> { where("date < ?", Time.now) }

  # default scope
  default_scope { order(:date) }

  # validations
  validates :name, :address, :date, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Associations
  has_many :events
  has_and_belongs_to_many :enrolled_events, class_name: 'Event'
  
  # Validations
  validates :name, :email, presence: true
  validates :password, length: { minimum: 6 }

  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  
  def login(user)
    session[:user_id] = user.id
  end

  def logout
    reset_session
  end

  def logged_in?
    current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include EventsHelper
  before_action :require_login, only: %i[index new show]

  def index
    @previous_events = Event.previous_events
    @upcoming_events = Event.upcoming_events
  end

  def show
    @event = Event.find params[:id]
    @attendees = @event.attendees
  end

  def new
    @event = current_user.events.new
  end

  def create
    @event = current_user.events.create event_params
    if @event.save
      flash[:success] = 'Event Created!'
      redirect_to @event
    else
      render :new
    end
  end

  def update
    @event = Event.find params[:id]
    @event.attendees << current_user
    flash[:success] = 'Thanks for Enrolling!'
    redirect_to current_user
  end

  private

  def event_params
    params.require(:event).permit(:name, :address, :date)
  end

  def require_login
    redirect_to sign_in_path unless logged_in?
    flash[:error] = 'Please, log in to create or view events!' unless logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :redirect_to_home_if_already_signed_in, only: [:new]
  
  def new; end

  def create
    user = User.find_by(email: params[:session][:email])
    if user&.authenticate(params[:session][:password])
      login(user)
      redirect_to events_path
    else
      flash.now[:error] = "Invalid login credentials"
      render :new
    end
  end

  def destroy
    logout
    redirect_to sign_in_path
  end

  private

  def redirect_to_home_if_already_signed_in
    redirect_to events_path if logged_in?
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :redirect_to_home_if_already_signed_in, only: [:new]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = 'You have successfully signed up!'
      redirect_to events_path
    else
      render new_user_path
    end
  end
  
  def show
    @user = User.find(params[:id])
    @enrolled_upcoming_events = @user.enrolled_events.upcoming_events
    
    get_user_previous_events
    get_user_upcoming_events
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def redirect_to_home_if_already_signed_in
    redirect_to events_path if logged_in?
  end

  def get_user_previous_events
    @previous_events = @user.events.previous_events
  end

  def get_user_upcoming_events
    @upcoming_events = @user.events.upcoming_events
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_header_if_user_logged_in
    render 'header' if logged_in?
  end

  def print_errors_if_any(object)
    render 'errors' if object.errors.any?
  end

end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def enrolled?(event)
    current_user.enrolled_events.exists?(event.id)
  end

  def verbose_time
    distance_of_time_in_words(@event.date, DateTime.now)
  end

  def validate_event_date
    if @event.date.today? || @event.date.future?
      render html: "The Event Will Start in #{verbose_time}"
    else
      render html: 'This Event has been archived'
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_errors.html.erb
<div class="alert-error">
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>  
</div>

app/views/application/_header.html.erb
<header>
  <div class='left'>
    <%= link_to 'Events', events_path %>
    <%= link_to 'Create Event', new_event_path %> 
  </div>
  
  <div class='right'>
    <%= link_to current_user.name, current_user %>
    <%= link_to 'Sign Out', session_path, method: :delete  %>
  </div>
</header>

app/views/events/index.html.erb
<h1>Amazing events you can attend</h1>
<% @upcoming_events.each do |event| %>
  <div class='event-box'>
    
    <div class="event-header">
      <h2 class="event-name"><%= link_to event.name, event %></h2>
      <p class="event-description">
        <%= event.description %>
      </p>
    </div>
    
    <div class="event-info">
      <p>
        <%= image_tag 'address.png' %>
        <%= event.address %>
      </p>
      
      <p>
        <%= image_tag 'date.png' %>
        <%= event.date.strftime("%B %d, %Y") %>
      </p>
      
      <p>
        <%= image_tag 'person.png' %>
        <%= link_to event.owner.name, event.owner %>
      </p>
    </div>

    <div class="enroll-btn">
      <%= button_to 'Enroll', event, method: :patch, disabled: enrolled?(event) %>
    </div>

  </div>
<% end %>

app/views/events/new.html.erb
<div class="events">

  <%= print_errors_if_any(@event) %>

  <div class="new-event-form">

    <h1 class="new-event-header">Create new event</h1>

    <%= form_for @event  do |f| %>
      <div>
        <%= f.text_field :name, placeholder: 'Enter event name', class: 'field' %>
      </div>

      <div>
        <%= f.text_field :address, placeholder: 'Enter event address', class: 'field' %>
      </div>

      <div>
        <%= f.date_field :date, class: 'field' %>
      </div>

      <div>
        <%= f.submit 'Add Event', class: 'submit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="show">
  <h1>Event information</h1>

  <div class="event-information">
    
    <div class="event-header">
      <h2 class="event-name">
        <%= @event.name %>
      </h2>
      <p class="event-description">
        <%= @event.description %>
      </p>
    </div>

    <div class="event-info">
      <p>
        <%= image_tag 'address.png' %>
        <%= @event.address %>
      </p>
      
      <p>
        <%= image_tag 'person.png' %>
        <%= link_to @event.owner.name, @event.owner %>
      </p>      
    </div>


    <p class="event-date">
      <%= validate_event_date %>
    </p>

  </div>

  <h2>List of Attendees</h2>

  <% unless @attendees.size.zero? %>
    <ol class="list">
      <% @attendees.each do |attendee| %>
        <li><%= attendee.name %></li>
      <% end %>
    </ol>
  <% else %>
    <p class="no-attendee">There are no attendees for <span><%= @event.name %></span> at this time.</p>
  <% end %>


  <div class="back-btn">
    <%= button_to 'Back to all events', events_path, method: :get %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>EventsIO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |key, value| %>
      <div class="alert-<%= key %>" >
        <p><%= value %></p>
      </div>
    <% end %>

    <%= show_header_if_user_logged_in %>

    <main class="<%= controller.controller_name %>">
      <%= yield %>
    </main>

    <footer>
      &copy; Copyright 2019 EventsIO.com
    </footer>
  
  </body>
</html>

app/views/users/_errors.html.erb
<div class="alert-error">
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<div class="sign-up">

  <%= print_errors_if_any(@user) %>

  <div class="head">
    <p class="logo">Events<span>IO</span></p>
    <p class="sign-up-btn"><%= link_to 'Sign In', new_session_path %></p>
  </div>

  <div class="signup-form">
    <h1 class='sign-up-header'>Sign Up</h1>
    <%= form_for @user do |f| %>
      <div>
        <%= f.text_field :name, placeholder: 'Name', class: 'field' %>
      </div>

      <div>
        <%= f.email_field :email, placeholder: 'Email', class: 'field' %>
      </div>

      <div>
        <%= f.password_field :password, placeholder: 'Password', class: 'field' %>
      </div>

      <div>
        <%= f.password_field :password_confirmation, placeholder: 'Confirm Password', class: 'field' %>
      </div>

      <div>
        <%= f.submit 'Sign Up', class: 'submit' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-users">
  <div class="enrolled-upcoming-events">
    
    <h2>Enrolled  Upcoming Events</h2>

    <div class="event-box">
      <% @enrolled_upcoming_events.each do |event| %>
        
        <div class="event-name">
          <%= link_to event.name, event %>
        </div>

        <div class="event-info">
          <p>
            <%= image_tag 'date.png' %>
            <%= event.date.strftime("%B %d, %Y") %>
          </p>
        </div>

      <% end %>
    </div>

  </div>

  <div class='events-details'>

    <div class="event-header">
      <% if @user == current_user %>
        <h2>Your Events</h2>
      <% else %>
        <h2><%= @user.name %>'s Events</h2>
      <% end %>
    </div>

    <div class="event-box">
      <div class="upcoming-events">
        <h3>Upcoming Events</h3>
        <% @upcoming_events.each do |event| %>

          <div class='event-name'>
            <%= link_to event.name, event %>
          </div>
          
        <% end %>
      </div>

      <div class="previous-events">
        <h3>Previous Events</h3>
        <% @previous_events.each do |event| %>

          <div class='event-name'>
            <%= link_to event.name, event %>
          </div>
          
        <% end %>
      </div>
    </div>

  </div>
</div>